using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Data.Entity;

namespace JimRadioMaint
{
    // Note: For instructions on enabling IIS6 or IIS7 classic mode, 
    // visit http://go.microsoft.com/?LinkId=9394801

    public class MvcApplication : System.Web.HttpApplication
    {
        public static void RegisterGlobalFilters(GlobalFilterCollection filters)
        {
            filters.Add(new HandleErrorAttribute());
        }

        public static void RegisterRoutes(RouteCollection routes)
        {
            routes.IgnoreRoute("{resource}.axd/{*pathInfo}");

            routes.MapRoute(
                "Default",                      // - route name
                "{controller}/{action}/{id}",   // - URL with parameters
                new { controller = "Home",      // - parameters and their defaults
                      action = "Index",
                      id = UrlParameter.Optional
                    }   
            );
        }

        protected void Application_Start()
        {
            //- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
            // NOTE: Default code generated by the Entity Framework.  This caused problems:
            // using System.Data.Entity.Database;
            // System.Data.Entity.Database.SetInitializer(
            // new System.Data.Entity.DropCreateDatabaseIfModelChanges<Models.Video.VideoDBContext>());
            //- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
            // The fix:
            Database.SetInitializer<JimRadioMaint.Models.Video.VideoDBContext>(null);
            //- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

            AreaRegistration.RegisterAllAreas();

            RegisterGlobalFilters(GlobalFilters.Filters);
            RegisterRoutes(RouteTable.Routes);
        }
    }
}